### ISSUE TITLE
Github Project Topics

### ISSUE THREAD

**Issue by tinohager** [marthijn/Sidio.Sitemap.AspNetCore#6]
I use before this package [SimpleMvcSitemap](https://github.com/uhaciogullari/SimpleMvcSitemap), it took me some time to find a good alternative before I found this great new package.

Can you add to you package this topic?
`generating-sitemaps`, `sitemap-files`

Maybe you can also write in the readme that it is uncomplicated to switch from the one package to yours.

**Comment by marthijn** [comment]
Work in progress, see: https://github.com/marthijn/Sidio.Sitemap.AspNetCore/wiki/Migrating-from-SimpleMvcSitemap
