### ISSUE TITLE
Sidio prefix reservation

### ISSUE THREAD

**Issue by tinohager** [marthijn/Sidio.Sitemap.AspNetCore#8]
# ID prefix reservation application process

1. Review the acceptance [criteria for prefix ID reservation](https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-criteria).
2. Determine the prefixes you want to reserve, in addition to any [advanced prefix reservation scenarios](https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) you may require.
3. Send a mail to [account@nuget.org](mailto:account@nuget.org) with the owner display name on [nuget.org](https://www.nuget.org/), as well as any reserved prefixes you are requesting. If you are delegating prefix subsets to multiple owners, make sure you mention all owner display names and prefix subsets.

After the application is submitted, you are notified of acceptance or rejection (with the criteria that caused rejection). We may need to ask additional identifying questions to confirm owner identity.

https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-application-process

**Comment by marthijn** [comment]
That went quickly:
![image](https://github.com/marthijn/Sidio.Sitemap.AspNetCore/assets/1124723/a0e03f45-322a-4baf-9bd0-8614904accfa)
